#pragma once
#include <stdint.h>
#include <stddef.h>

// Otto eye animations (240x240 GIFs), in the order of `enum Face` in main.cpp.
// Data lives in src/otto_gifs.cpp, generated by mascot/otto/gen_otto_gifs.py.
struct OttoGif {
    const uint8_t* data;
    size_t         len;
};

#define OTTO_GIF_COUNT 6
extern const OttoGif OTTO_GIFS[OTTO_GIF_COUNT];
