"""Turn mascot/otto/*.gif into src/otto_gifs.cpp (const arrays, kept in flash).

Run from HS-01/chatbot:  python3 mascot/otto/gen_otto_gifs.py
"""
from pathlib import Path

ORDER = ["neutral", "surprised", "thinking", "happy", "sad", "confused"]  # == enum Face
here = Path(__file__).parent
out = here.parent.parent / "src" / "otto_gifs.cpp"

lines = [
    "// Generated by mascot/otto/gen_otto_gifs.py — do not edit.",
    "// Otto eye GIFs (c) 2025 小鹏, MIT License: https://github.com/txp666/otto-emoji-gif-component",
    '#include "otto_gifs.h"',
    "",
]
for name in ORDER:
    data = (here / f"{name}.gif").read_bytes()
    lines.append(f"static const uint8_t {name}_gif[{len(data)}] = {{")
    for i in range(0, len(data), 24):
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 24]) + ",")
    lines.append("};")
lines.append("")
lines.append("const OttoGif OTTO_GIFS[OTTO_GIF_COUNT] = {")
lines += [f"    {{ {n}_gif, sizeof({n}_gif) }},  // {n}" for n in ORDER]
lines.append("};")
out.write_text("\n".join(lines) + "\n")
print(f"wrote {out} ({sum((here / f'{n}.gif').stat().st_size for n in ORDER)} bytes of GIF)")
